import {describe,it,expect} from 'vitest';
import {mkdtemp,mkdir,writeFile,readFile,rm,stat,readdir} from 'node:fs/promises';
import {join,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {versionParts,compareVersions,installedVersion,stageAndActivate,selectedEntry} from '../apps/launcher/dsh-policy.mjs';
import {privateJson,parseLaunch,doctor} from '../apps/launcher/main.mjs';
async function fixture(entry:string,version:string){await mkdir(dirname(entry),{recursive:true});await writeFile(entry,'');await writeFile(join(dirname(entry),'../package.json'),JSON.stringify({name:'@deepseek-ai/dsh',version}));}
describe('DSH latest policy',()=>{
 it('accepts prerelease registry tags resolved to exact safe semver only',()=>{for(const good of ['0.1.5-rc.1','1.0.0','1.0.0+build.2'])expect(()=>versionParts(good)).not.toThrow();for(const bad of ['latest','v1.0.0','1.0.0;echo bad','../foo','1.0.0-01','01.0.0',{}])expect(()=>versionParts(bad)).toThrow();});
 it('does not downgrade rc.2 to registry latest rc.1 and orders semver identifiers',()=>{expect(compareVersions('0.1.5-rc.1','0.1.5-rc.2')).toBe(-1);expect(compareVersions('1.0.0','1.0.0-rc.10')).toBe(1);expect(compareVersions('1.0.0-rc.10','1.0.0-rc.2')).toBe(1);expect(compareVersions('1.0.0+a','1.0.0+b')).toBe(0);});
 it('only updates with explicit startup flag',()=>{expect(parseLaunch(['--update-dsh','--yes']).updateDsh).toBe(true);expect(parseLaunch([]).updateDsh).toBeUndefined();});
 it('reports actual installed versions rather than baseline and accepts newer manifests',async()=>{const home=await mkdtemp(join(tmpdir(),'turnwire-policy-'));try{const entry=join(home,'runtime/node_modules/@deepseek-ai/dsh/lib/bin.js');await fixture(entry,'99.1.0');expect(await installedVersion(entry)).toBe('99.1.0');const result=await doctor({env:{HOME:home,TURNWIRE_DSH_ENTRY:entry}});expect(result.dshVersion).toBe('99.1.0');expect(result.dshBaselineVersion).toBe('0.1.5-rc.2');}finally{await rm(home,{recursive:true,force:true});}});
 it('stages exact version, preserves old selection on failed probe, activates only on success',async()=>{const home=await mkdtemp(join(tmpdir(),'turnwire-policy-'));try{const paths={data:join(home,'data'),cache:join(home,'cache'),config:join(home,'config'),dshEntry:join(home,'old/node_modules/@deepseek-ai/dsh/lib/bin.js')};await fixture(paths.dshEntry,'1.0.0');await mkdir(paths.config);const pointer=join(paths.config,'managed-dsh.json');await writeFile(pointer,'{"old":"untouched"}',{mode:0o600});const runChild=async(_exe:string,args:string[])=>{expect(args).toContain('@deepseek-ai/dsh@2.0.0');expect(args).toContain('--ignore-scripts');await fixture(join(args[args.indexOf('--prefix')+1]!,'node_modules/@deepseek-ai/dsh/lib/bin.js'),'2.0.0');return 0;};const options={paths,version:'2.0.0',root:home,env:{},runChild,probe:async()=>{}};await expect(stageAndActivate({...options,smoke:async()=>{throw Error('incompatible');}})).rejects.toThrow('incompatible');expect(await readFile(pointer,'utf8')).toBe('{"old":"untouched"}');expect(await readdir(join(paths.data,'runtime/dsh-versions'))).toEqual([]);const entry=await stageAndActivate({...options,smoke:async()=>{expect(await readFile(pointer,'utf8')).toBe('{"old":"untouched"}');}});expect(await selectedEntry(paths,{},privateJson)).toBe(entry);expect((await stat(pointer)).mode&0o777).toBe(0o600);expect(await installedVersion(paths.dshEntry)).toBe('1.0.0');}finally{await rm(home,{recursive:true,force:true});}});
});
