import { afterEach, expect, it, vi } from 'vitest';
import { mkdtemp, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createECDH, randomBytes } from 'node:crypto';
import { TurnwireCore, Store } from '@turnwire/core';
import { DemoRuntime } from '@turnwire/runtime';
import { LocalClient, RemoteClient, randomSecret } from '@turnwire/sdk';
import type { NotificationStatus, Session, Snapshot, InboxPage } from '@turnwire/protocol';
import { RelayPush, validatePushEndpoint } from '../apps/relay/src/push.js';
import { startRelay } from '../apps/relay/src/server.js';
import { RemoteController } from '../apps/daemon/src/remote-control.js';
import { startDaemonServer } from '../apps/daemon/src/server.js';
let cleanup: Array<() => unknown> = [];
afterEach(async () => { for (const close of cleanup.reverse()) await close(); cleanup = []; });
const subscription = () => { const ecdh = createECDH('prime256v1'); ecdh.generateKeys(); return { endpoint: 'https://web.push.apple.com/test-endpoint', keys: { p256dh: ecdh.getPublicKey().toString('base64url'), auth: randomBytes(16).toString('base64url') } }; };
it('persists the VAPID identity and queue, deduplicates delivery and removes expired subscriptions', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'turnwire-push-')); cleanup.push(() => rm(directory, { recursive: true, force: true }));
  const path = join(directory, 'push.db');
  let push = new RelayPush(path, 'https://relay.example'); const publicKey = push.publicKey;
  const allowed = new Set(['phone']); const handle = (action: string, rest = {}) => push.handle('host', allowed, { type: 'push.request', id: crypto.randomUUID(), action, ...rest });
  handle('subscribe', { clientId: 'phone', subscription: subscription() }); handle('notify', { clientId: 'phone', notificationId: 'one' });
  await push.close();
  const deliver = vi.fn().mockResolvedValue({ statusCode: 201, headers: {}, body: '' });
  push = new RelayPush(path, 'https://relay.example', deliver); cleanup.push(() => push.close());
  expect(push.publicKey).toBe(publicKey); expect((await stat(path)).mode & 0o777).toBe(0o600);
  await push.flush(); expect(deliver).toHaveBeenCalledTimes(1);
  expect(deliver.mock.calls[0]?.[1]).not.toContain('approval');
  handle('notify', { clientId: 'phone', notificationId: 'one' }); await push.flush(); expect(deliver).toHaveBeenCalledTimes(1);
  deliver.mockRejectedValueOnce({ statusCode: 410 }); handle('notify', { clientId: 'phone', notificationId: 'two' }); await push.flush();
  expect(handle('status', { clientId: 'phone' })).toMatchObject({ subscribed: false, queued: 0 });
  expect(() => handle('subscribe', { clientId: 'other', subscription: subscription() })).toThrow();
  for (const endpoint of ['http://127.0.0.1/', 'https://192.168.1.2/', 'https://web.push.apple.com.evil.test/', 'https://web.push.apple.com:9898/', 'https://secret@web.push.apple.com/']) expect(() => validatePushEndpoint(endpoint)).toThrow();
});
it('uses the encrypted device identity for subscriptions and delivers generic approval hints from a durable inbox', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'turnwire-inbox-')); cleanup.push(() => rm(directory, { recursive: true, force: true }));
  const store = new Store(join(directory, 'state.db')); const core = new TurnwireCore(store, [new DemoRuntime()], { id: 'host', name: 'Host' }); cleanup.push(() => core.dispose());
  const token = randomSecret(); const deliver = vi.fn().mockResolvedValue({ statusCode: 201, headers: {}, body: '' });
  const relay = await startRelay({ token, port: 0, push: { path: join(directory, 'push.db'), subject: 'https://relay.example', deliver } }); cleanup.push(() => relay.close());
  const remote = new RemoteController(core, { directory, webRoot: directory, initialRelay: { relayUrl: `ws://127.0.0.1:${relay.port}`, token, remoteUrl: `http://127.0.0.1:${relay.port}` } }); cleanup.push(() => remote.close()); remote.start();
  const server = await startDaemonServer({ core, token, port: 0, remoteAccess: remote }); cleanup.push(() => server.close());
  const local = new LocalClient(`http://127.0.0.1:${server.port}`, token); cleanup.push(() => local.close());
  await vi.waitFor(() => expect(remote.status().state).toBe('online'), { timeout: 15_000 });
  const invitation = await local.pairDevice('Phone'); await vi.waitFor(() => expect(remote.status().state).toBe('online'), { timeout: 15_000 });
  const phone = new RemoteClient(invitation.pairing); cleanup.push(() => phone.close());
  expect((await phone.request<NotificationStatus>('notifications.status')).available).toBe(true);
  await expect(local.request('notifications.subscribe', subscription())).rejects.toThrow('paired phone');
  expect(await phone.request('notifications.subscribe', subscription())).toMatchObject({ subscribed: true });
  const s = await local.request<Session>('session.create', { title: 'Private title', cwd: directory, runtimeId: 'demo' });
  const requestId = crypto.randomUUID(); const receipt = await phone.request('session.message', { sessionId: s.id, text: 'approval' }, requestId);
  expect(await local.request('request.result', { requestId })).toMatchObject({ state: 'completed', response: { result: receipt } });
  phone.suspend(); await remote.notifications.flush(); await vi.waitFor(() => expect(deliver).toHaveBeenCalledTimes(1), { timeout: 4000 });
  expect(JSON.stringify(deliver.mock.calls[0]?.[1])).not.toContain('Private title');
  const inbox = await local.request<InboxPage>('inbox.page'); expect(inbox.items).toHaveLength(1);
  const id = inbox.items[0]!.approval.id;
  await local.request('approval.decide', { approvalId: id, decision: 'approved' });
  expect((await local.request<InboxPage>('inbox.page')).items).toHaveLength(0);
  expect((await local.request<InboxPage>('inbox.page', { status: 'all' })).items[0]?.approval.status).toBe('approved');
  await expect(local.request('approval.decide', { approvalId: id, decision: 'rejected' })).rejects.toThrow('already handled');
  await local.configureNotifications(false); expect(remote.notifications.status().enabled).toBe(false);
  expect((await local.request<Snapshot>('system.snapshot')).sessions[0]?.id).toBe(s.id);
});
it('keeps cancelled approvals visible after a daemon restart', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'turnwire-inbox-restart-')); cleanup.push(() => rm(directory, { recursive: true, force: true }));
  const path = join(directory, 'state.db'); let core = new TurnwireCore(new Store(path), [new DemoRuntime()], { id: 'host', name: 'Host' });
  const request = (method: string, params = {}) => core.handle({ v: 1, id: crypto.randomUUID(), method, params });
  const result = await request('session.create', { title: 'Test', cwd: directory, runtimeId: 'demo' }); if (!result.ok) throw new Error('Create failed');
  await request('session.message', { sessionId: (result.result as Session).id, text: 'approval' });
  await core.dispose(); core = new TurnwireCore(new Store(path), [new DemoRuntime()], { id: 'host', name: 'Host' }); cleanup.push(() => core.dispose()); await core.start();
  expect(core.store.inbox(40, 'pending').items).toHaveLength(0);
  expect(core.store.inbox(40, 'all').items[0]?.approval.status).toBe('cancelled');
});
