// Isolated production-source App fixture: temporary build only; never touches product dist or services.
import { build } from 'vite';
import react from '@vitejs/plugin-react';
import { chromium, expect } from '@playwright/test';
import { createServer } from 'node:http';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve, join, extname } from 'node:path';
import { tmpdir } from 'node:os';
import { hermeticEnv } from './helpers/hermetic-env.mjs';
const root = resolve(import.meta.dirname, '..');
const temporary = await mkdtemp(join(tmpdir(), 'turnwire-session-browser-'));
const entry = join(temporary, 'index.html');
await writeFile(entry, `<meta name="viewport" content="width=device-width, initial-scale=1"><div id="root"></div><script type="module" src="${root}/tests/fixtures/session-management.tsx"></script>`);
let browser; let server;
try {
  await build({ configFile: false, root: temporary, plugins: [react()], resolve: { alias: { 'react': resolve(root, 'node_modules/react'), 'react-dom': resolve(root, 'node_modules/react-dom'), '@turnwire/sdk': resolve(root, 'tests/fixtures/session-management-sdk.ts'), '@turnwire/protocol': resolve(root, 'packages/protocol/src/index.ts'), '@turnwire/wire': resolve(root, 'packages/wire/src/index.ts') } }, build: { outDir: join(temporary, 'build'), emptyOutDir: true, rollupOptions: { input: entry } } });
  server = createServer(async (request, response) => { try { const file = join(temporary, 'build', request.url.split('?')[0] === '/' ? 'index.html' : request.url.split('?')[0]); response.setHeader('Content-Type', ({ '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' })[extname(file)] ?? 'application/octet-stream'); response.end(await readFile(file)); } catch { response.writeHead(404); response.end(); } });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  browser = await chromium.launch({ channel: 'chrome', headless: true, env: hermeticEnv(temporary) });
  for (const width of [320, 390, 1280]) {
    const page = await browser.newPage({ viewport: { width, height: 844 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    await expect(page.locator('.session-heading h1')).toHaveText('Selected conversation');
    await expect(page.locator('.context-usage summary')).toHaveAttribute('aria-label', /Context ≈ 42,000 \/ 128,000 · 32.8%/);
    await expect(page.locator('.context-usage summary')).toHaveAttribute('title', /Estimated next request/);
    await expect(page.locator('.context-usage summary')).toHaveText('');
    await expect(page.locator('.context-ring-value')).toHaveAttribute('stroke-dasharray', '32.8125 100');
    await expect(page.locator('.composer-bottom .context-usage')).toHaveCount(1);
    await expect(page.locator('.composer-utility-row .image-picker')).toHaveCount(1);
    await expect(page.locator('.composer-utility-row .approval-mode')).toHaveCount(1);
    expect(await page.locator('.composer').evaluate(el => {
      const approval = el.querySelector('.approval-mode').getBoundingClientRect();
      const image = el.querySelector('.image-picker').getBoundingClientRect();
      const input = el.querySelector('textarea'); const style = getComputedStyle(input);
      const lineCenter = input.getBoundingClientRect().top + parseFloat(style.paddingTop) + parseFloat(style.lineHeight) / 2;
      return approval.right <= image.left && Math.abs(lineCenter - (image.top + image.height / 2)) < 3;
    })).toBe(true);
    await page.locator('.context-usage summary').click();
    await expect(page.locator('.context-detail')).toBeVisible();
    expect(await page.locator('.context-detail').evaluate(el => { const r = el.getBoundingClientRect(); return el.parentElement === document.body && r.left >= 0 && r.right <= innerWidth && r.top >= 0 && r.bottom <= innerHeight && [[r.left + 4, r.top + 4], [r.right - 4, r.bottom - 4], [r.left + r.width / 2, r.top + r.height / 2]].every(([x, y]) => el.contains(document.elementFromPoint(x, y))); })).toBe(true);
    await page.keyboard.press('Escape');
    await expect(page.locator('.context-detail')).toBeHidden();
    await expect(page.locator('.context-usage summary')).toBeFocused();
    await page.locator('.context-usage summary').click();
    await page.locator('.session-heading h1').click();
    await expect(page.locator('.context-detail')).toBeHidden();
    await expect(page.locator('.composer-status-line .locale-switch')).toHaveCount(0);
    await expect(page.locator('.sidebar .locale-switch')).toHaveCount(0);
    await expect(page.locator('.runtime-identity')).toContainText('Fixture runtime');
    await expect(page.locator('.session-heading .context-usage')).toHaveCount(0);
    await expect(page.locator('.topbar-right .runtime-identity')).toContainText('Fixture runtime');
    expect(await page.locator('.composer-utility-row .approval-mode button').evaluate(el => el.getBoundingClientRect().width <= 34)).toBe(true);
    await expect(page.locator('.composer-status-line')).toHaveCount(0);
    expect(await page.locator('.composer-utility-row').evaluate(element => { const children = [...element.children].map(child => child.getBoundingClientRect()).filter(r => r.width > 0 && r.height > 0); return Math.max(...children.map(r => r.top + r.height / 2)) - Math.min(...children.map(r => r.top + r.height / 2)) < 2 && element.getBoundingClientRect().right <= innerWidth; })).toBe(true);
    const idleQueue = page.locator('.queued-item').filter({ hasText: 'Idle pending message' });
    await expect(idleQueue.getByRole('button', { name: 'Steer', exact: true })).toBeDisabled();
    if (width < 700) await page.getByRole('button', { name: 'Open session list', exact: true }).click();
    await page.locator('[data-session-id="running"] .session-row').click();
    const adjust = page.locator('.queued-item').filter({ hasText: 'Adjust current work' });
    await expect(adjust).toHaveAttribute('data-queue-target', 'next-turn');
    await adjust.getByRole('button', { name: 'Steer', exact: true }).click();
    await expect(adjust).toHaveAttribute('data-queue-target', 'next-step');
    await expect(adjust).toContainText('Steering pending · after the current step');
    await expect(adjust.getByRole('button', { name: 'Steer', exact: true })).toBeDisabled();
    await expect(page.locator('.queued-item').first()).toContainText('Adjust current work');
    await page.evaluate(() => { window.fixture.queueFail = true; });
    await expect.poll(() => page.evaluate(() => window.fixture.queueFailures), { timeout: 10000 }).toBeGreaterThan(0);
    await expect(adjust).toHaveAttribute('data-queue-target', 'next-step');
    await expect(page.locator('.queued-item')).toHaveCount(2);
    await page.evaluate(() => { window.fixture.queueFail = false; });
    await expect(page.locator('.queued-item').filter({ hasText: 'Ordinary queued message' })).toHaveAttribute('data-queue-target', 'next-turn');
    if (width < 700) await page.getByRole('button', { name: 'Open session list', exact: true }).click();
    await page.locator('[data-session-id="one"] .session-row').click();
    const composer = page.locator('.composer textarea'); await composer.fill('Keep my draft');
    await expect(page.locator('.topbar details')).toHaveCount(0);
    const mobile = width < 700;
    if (mobile) await page.getByRole('button', { name: 'Open session list', exact: true }).click();
    const row = id => page.locator(`[data-session-id="${id}"]`);
    const menu = page.locator('.session-row-menu');
    // Keyboard activation does not send pointerdown: only list-owned open identity can close A.
    await row('one').locator('.session-more').focus(); await page.keyboard.press('Enter');
    await row('two').locator('.session-more').focus(); await page.keyboard.press('Enter');
    await expect(menu).toHaveCount(1);
    await expect(row('one').locator('.session-more')).toHaveAttribute('aria-expanded', 'false');
    await expect(row('two').locator('.session-more')).toHaveAttribute('aria-expanded', 'true');
    await page.keyboard.press('Escape');
    await expect(menu).toHaveCount(0); await expect(row('two').locator('.session-more')).toBeFocused();
    if (mobile) await expect(page.locator('.sidebar')).toHaveClass(/visible/);
    await page.keyboard.press('Enter');
    await expect(menu).toHaveAttribute('aria-label', 'Manage session Other conversation');
    await menu.getByRole('button', { name: 'Rename', exact: true }).click();
    await menu.getByLabel('New session name').fill('  ');
    await expect(menu.getByRole('button', { name: 'Save name' })).toBeDisabled();
    await menu.getByLabel('New session name').fill('Renamed other');
    await page.evaluate(() => { window.fixture.fail = true; });
    await menu.getByRole('button', { name: 'Save name' }).click();
    const failure = menu.getByRole('alert');
    await expect(failure).toContainText('Fixture management failure');
    await expect(failure).toContainText('Other conversation');
    await expect(failure).toBeVisible();
    expect(await failure.evaluate(element => {
      const box = element.getBoundingClientRect();
      return box.top >= 0 && box.bottom <= innerHeight && box.left >= 0 && box.right <= innerWidth && element.contains(document.elementFromPoint(box.left + box.width / 2, box.top + box.height / 2));
    })).toBe(true);
    await expect(page.locator('main [role="alert"]')).toHaveCount(0);
    await expect(menu.getByLabel('New session name')).toHaveValue('Renamed other');
    await page.evaluate(() => { window.fixture.fail = false; window.fixture.delay = 250; });
    await menu.getByRole('button', { name: 'Save name' }).click();
    await expect(menu.getByRole('button', { name: 'Save name' })).toBeDisabled();
    await expect(row('two').locator('strong')).toHaveText('Renamed other');
    await expect(menu).toHaveCount(0);
    expect(await page.evaluate(() => window.fixture.calls.filter(call => call.method === 'session.rename').map(call => call.sessionId))).toEqual(['two', 'two']);
    await expect(row('one').locator('.session-row')).toHaveAttribute('aria-current', 'page');
    await expect(composer).toHaveValue('Keep my draft');
    // A late success cannot close a newer B menu; a late error remains owned by A.
    for (const fail of [false, true]) {
      await page.evaluate(fail => { window.fixture.fail = fail; window.fixture.delay = 300; }, fail);
      await row('two').locator('.session-more').click();
      await menu.getByRole('button', { name: 'Rename', exact: true }).click();
      await menu.getByLabel('New session name').fill('Renamed other');
      await menu.getByRole('button', { name: 'Save name' }).click();
      await row('one').locator('.session-more').focus(); await page.keyboard.press('Enter');
      await expect(menu).toHaveAttribute('aria-label', 'Manage session Selected conversation');
      await expect(menu.getByRole('button', { name: 'Rename', exact: true })).toBeEnabled();
      if (fail) await expect(page.locator('[data-error-session-id="two"]')).toBeVisible();
      else await expect.poll(() => page.evaluate(() => window.fixture.completed)).toBeGreaterThanOrEqual(3);
      await expect(menu).toHaveAttribute('aria-label', 'Manage session Selected conversation');
      await expect(menu.getByRole('alert')).toHaveCount(0);
      await expect(menu.getByRole('button', { name: 'Rename', exact: true })).toBeFocused();
      await expect(composer).toHaveValue('Keep my draft');
      await page.keyboard.press('Escape');
      if (fail) await page.getByRole('button', { name: 'Dismiss error' }).click();
    }
    // Filtering unmounts A; its operation result must still be available in the list.
    await page.evaluate(() => { window.fixture.fail = true; window.fixture.delay = 300; });
    await row('two').locator('.session-more').click();
    await menu.getByRole('button', { name: 'Save name' }).click();
    await page.getByRole('button', { name: 'Archived', exact: true }).click();
    await expect(row('two')).toHaveCount(0);
    await expect(page.locator('nav [data-error-session-id="two"]')).toBeVisible();
    await expect(composer).toHaveValue('Keep my draft');
    await page.getByRole('button', { name: 'Dismiss error' }).click();
    await page.getByRole('button', { name: 'Work sessions', exact: true }).click();
    await page.evaluate(() => { window.fixture.fail = false; window.fixture.delay = 0; });
    await row('two').locator('.session-more').click();
    await expect(menu.getByLabel('New session name')).toHaveValue('Renamed other');
    await menu.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.keyboard.press('Enter');
    await page.keyboard.press('Escape');
    await expect(menu).toHaveCount(0); await expect(row('two').locator('.session-more')).toBeFocused();
    if (mobile) await expect(page.locator('.sidebar')).toHaveClass(/visible/);
    await row('two').locator('.session-more').click();
    await page.locator('.brand').dispatchEvent('pointerdown', { bubbles: true }); await expect(menu).toHaveCount(0);
    for (const id of ['running', 'approval']) {
      await row(id).locator('.session-more').click();
      await expect(menu.getByRole('button', { name: 'Archive session', exact: true })).toBeDisabled();
      await expect(menu.getByRole('button', { name: 'Rename', exact: true })).toBeEnabled();
      await page.keyboard.press('Escape');
    }
    await row('two').locator('.session-more').click();
    await page.evaluate(() => window.fixture.offline(true));
    await expect(menu.getByRole('button', { name: 'Rename', exact: true })).toBeDisabled();
    await expect(menu.getByRole('button', { name: 'Archive session', exact: true })).toBeDisabled();
    await page.evaluate(() => window.fixture.offline(false));
    await menu.getByRole('button', { name: 'Archive session', exact: true }).click();
    await expect(row('two')).toHaveCount(0);
    await expect(page.locator('nav.session-list')).toBeFocused();
    await expect(composer).toHaveValue('Keep my draft');
    await page.getByRole('button', { name: 'Archived', exact: true }).click();
    await row('two').locator('.session-more').click();
    await expect(menu.getByRole('button', { name: 'Rename', exact: true })).toBeEnabled();
    await menu.getByRole('button', { name: 'Unarchive', exact: true }).click();
    await expect(row('two')).toHaveCount(0);
    await expect(page.locator('nav.session-list')).toBeFocused();
    await expect(composer).toHaveValue('Keep my draft');
    const calls = await page.evaluate(() => window.fixture.calls.filter(call => call.method === 'session.archive'));
    expect(calls.map(call => [call.sessionId, call.archived])).toEqual([['two', true], ['two', false]]);
    await row('archived').locator('.session-row').click();
    await expect(page.locator('.composer-attachments')).toContainText('This session is archived');
    await expect(page.locator('.composer-area').getByRole('button', { name: 'Unarchive' })).toHaveCount(0);
    await expect(composer).toBeDisabled();
    if (mobile) await page.getByRole('button', { name: 'Open session list', exact: true }).click();
    await page.getByRole('button', { name: 'Work sessions', exact: true }).click();
    await row('two').locator('.session-more').click(); await menu.getByRole('button', { name: 'Rename', exact: true }).click();
    await menu.getByLabel('New session name').fill('LongUnbrokenTitle'.repeat(30));
    const geometry = await menu.evaluate(element => ({ left: element.getBoundingClientRect().left, right: element.getBoundingClientRect().right, overflow: element.scrollWidth > element.clientWidth + 1, inputFont: getComputedStyle(element.querySelector('input')).fontSize }));
    expect(geometry.left).toBeGreaterThanOrEqual(0); expect(geometry.right).toBeLessThanOrEqual(width); expect(geometry.overflow).toBe(false);
    if (mobile) {
      expect(geometry.inputFont).toBe('16px');
      await page.keyboard.press('Escape');
      const controls = page.locator('.sidebar button:visible:not(:disabled)');
      await controls.last().focus(); await page.keyboard.press('Tab'); await expect(controls.first()).toBeFocused();
      await page.keyboard.press('Shift+Tab'); await expect(controls.last()).toBeFocused();
      await page.keyboard.press('Escape'); await expect(page.locator('.sidebar')).not.toHaveClass(/visible/);
      await expect(page.getByRole('button', { name: 'Open session list', exact: true })).toBeFocused();
    }
    expect(errors).toEqual([]);
    await page.close();
    const settings = await browser.newPage({ viewport: { width, height: 844 } });
    await settings.goto(`http://127.0.0.1:${server.address().port}`);
    await settings.getByRole('button', { name: 'Settings', exact: true }).click();
    await expect(settings.locator('.connection-view input[type="password"]')).toHaveCount(0);
    await expect(settings.locator('.connection-view textarea')).toHaveCount(0);
    const remember = settings.getByRole('checkbox', { name: 'Remember connection in this browser', exact: true });
    await expect(remember).not.toBeChecked();
    await settings.evaluate(() => { window.originalStorageSetItem = Storage.prototype.setItem; Storage.prototype.setItem = function(key, value) { if (key === 'turnwire.connection') throw new DOMException('Blocked', 'QuotaExceededError'); return window.originalStorageSetItem.call(this, key, value); }; });
    await remember.check().catch(() => {});
    await expect(remember).not.toBeChecked();
    expect(await settings.evaluate(() => !!sessionStorage.getItem('turnwire.connection') && !localStorage.getItem('turnwire.connection'))).toBe(true);
    await settings.evaluate(() => { Storage.prototype.setItem = window.originalStorageSetItem; });
    await remember.check();
    expect(await settings.evaluate(() => !!localStorage.getItem('turnwire.connection') && !sessionStorage.getItem('turnwire.connection'))).toBe(true);
    await remember.uncheck();
    expect(await settings.evaluate(() => !localStorage.getItem('turnwire.connection') && !!sessionStorage.getItem('turnwire.connection'))).toBe(true);
    await settings.getByRole('button', { name: 'Replace connection', exact: true }).click();
    await expect(settings.locator('.connection-form input[type="password"]')).toHaveValue('');
    await settings.getByRole('button', { name: 'Cancel', exact: true }).click();
    await expect(settings.locator('.connection-current')).toBeVisible();
    expect(await settings.evaluate(() => JSON.parse(sessionStorage.getItem('turnwire.connection')).token)).toBe('fixture');
    await settings.close();
    const throwing = await browser.newPage({ viewport: { width, height: 844 } });
    await throwing.goto(`http://127.0.0.1:${server.address().port}/?throwing-manager`);
    await throwing.locator('[data-session-id="two"] .session-more').click();
    await throwing.getByRole('button', { name: 'Rename', exact: true }).click();
    await throwing.getByLabel('New session name').fill('Preserved after throw');
    for (let retry = 0; retry < 2; retry++) {
      await throwing.getByRole('button', { name: 'Save name' }).click();
      await expect(throwing.getByRole('alert')).toContainText('Thrown manager failure');
      await expect(throwing.getByRole('button', { name: 'Save name' })).toBeEnabled();
      await expect(throwing.getByLabel('New session name')).toHaveValue('Preserved after throw');
    }
    await throwing.close();
    console.log(`PASS ${width}: non-selected rename/archive/unarchive, draft, failure/busy/offline, running/approval, Escape/outside, drawer focus, archived composer, layout`);
  }
} finally { await browser?.close(); if (server) await new Promise(resolve => server.close(resolve)); await rm(temporary, { recursive: true, force: true }); }
