import { chromium, expect } from '@playwright/test';
import { readFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

const config = JSON.parse(await readFile(join(process.env.TURNWIRE_HOME ?? '/tmp/turnwire-preview-state', 'client.json'), 'utf8'));
const output = process.env.TURNWIRE_SCREENSHOTS ?? '/tmp/turnwire-screenshots';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const page = await context.newPage(); const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(config.url);
  await expect(page.getByRole('heading', { name: '连接，继续工作。' })).toBeVisible();
  await page.screenshot({ path: join(output, 'desktop-connection.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: '本机连接', exact: true }).click();
  await page.getByLabel('主机服务地址', { exact: true }).fill(config.url);
  await page.getByLabel('连接令牌', { exact: true }).fill(config.token);
  await page.getByRole('button', { name: '连接主机', exact: true }).click();
  await expect(page.getByText('已连接', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: /新建会话/ }).first().click();
  await page.getByLabel('会话名称').fill('验证 Turnwire 的多端接续');
  await page.getByLabel('工作目录').fill(process.cwd());
  await page.getByRole('button', { name: '创建会话', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: '验证 Turnwire 的多端接续' })).toBeVisible();
  await page.getByRole('textbox', { name: '消息', exact: true }).fill('验证消息与审批能否在 Mac 和手机之间同步。');
  await page.getByRole('button', { name: '发送消息', exact: true }).click();
  await expect(page.getByRole('button', { name: '批准本次', exact: true })).toBeVisible();
  await expect(page.getByText('这是 Turnwire 的离线演示会话。', { exact: false })).toBeVisible();
  await page.screenshot({ path: join(output, 'desktop-session.png'), fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  await page.screenshot({ path: join(output, 'mobile-approval.png'), fullPage: true, animations: 'disabled' });
  const overflowing = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
  expect(overflowing).toBe(false);
  await page.getByRole('button', { name: '批准本次', exact: true }).click();
  await expect(page.getByRole('button', { name: '批准本次', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '打开会话列表' }).click();
  await expect(page.getByRole('navigation', { name: '会话列表' })).toBeVisible();
  await page.getByRole('button', { name: '关闭列表', exact: true }).click();
  await page.setViewportSize({ width: 375, height: 667 });
  await expect(page.getByRole('textbox', { name: '消息', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: join(output, 'mobile-session-small.png'), fullPage: true, animations: 'disabled' });
  await page.reload();
  await expect(page.getByRole('heading', { name: '验证 Turnwire 的多端接续' })).toBeVisible();
  await expect(page.getByText('这是 Turnwire 的离线演示会话。', { exact: false })).toBeVisible();
  await page.locator('.session-actions summary').click();
  await page.getByRole('button', { name: '重命名', exact: true }).click();
  await page.getByLabel('新的会话名称').fill('跨端会话管理验证');
  await page.getByRole('button', { name: '保存名称', exact: true }).click();
  await expect(page.getByRole('heading', { name: '跨端会话管理验证' })).toBeVisible();
  await page.getByRole('button', { name: '归档会话', exact: true }).click();
  await expect(page.getByText('会话已归档，历史记录仍可查看。')).toBeVisible();
  await expect(page.getByRole('textbox', { name: '消息', exact: true })).toBeDisabled();
  await page.locator('.session-actions summary').click();
  await page.locator('.composer-area').getByRole('button', { name: '取消归档', exact: true }).click();
  await expect(page.getByRole('textbox', { name: '消息', exact: true })).toBeEnabled();
  expect(errors).toEqual([]);
  console.log('UI checks passed: connection, create, prompt, approval, responsive layout, persisted history.');
  console.log(`Screenshots: ${output}`);
} catch (error) {
  await page.screenshot({ path: join(output, 'failure.png'), fullPage: true, animations: 'disabled' });
  console.error(await page.locator('main').innerText());
  throw error;
} finally { await browser.close(); }
